baseURL      = 'https://zmlio.netlify.app/'
languageCode = 'en-us'
title        = 'zmlio'


[params]
  description = "Ainul Muzammil Portfolio Site"
  keywords    = "Ainul Muzammil, personal website, blog, portfolio"

  [params.author]
    name = 'Ainul Muzammil'


# Add theme using Hugo modules
[module]
  [[module.imports]]
    path = "github.com/hugo-porto/theme"
